# Generated by ezci - do not edit
# Updated: 2026-02-13 18:18:43

export PATH="$(dirname "$__EZCI_BIN"):/nix/store/r4rhh78ml6niaya5rfdf98yfnn5vi1s5-nix-unit-2.30.0/bin:/home/juliendauliac/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/local/sbin:/home/juliendauliac/ghq/git.manomano.tech/julien.dauliac/ezci/cli/target/release:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/juliendauliac/.local/share/npm-packages/bin/:/home/juliendauliac/_mkMergedOptionModule"

# Shell hook (runs once per session)
if [[ -z "${__EZCI_HOOK_RAN+x}" ]]; then
  export __EZCI_HOOK_RAN=1
  echo "nix-unit test scenario"
  echo "Run tests: nix run .#test"
fi
